[package]
name = "leetcode-cn"
version = "0.1.0"
authors = ["hybo <52079867+me1ting@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
